@TestOn('browser')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test -e Environment.browser --genHtml`

import './unit/branch_test.dart' as unit_branch_test;
import './unit/compose_test.dart' as unit_compose_test;
import './unit/with_props_test.dart' as unit_with_props_test;
import 'package:test/test.dart';
import 'package:react/react_client.dart' as react_client;
import 'package:over_react/over_react.dart';

void main() {
  react_client.setClientConfiguration();
  enableTestMode();
  unit_branch_test.main();
  unit_compose_test.main();
  unit_with_props_test.main();
}
