language: dart
dart_task:
  - test: --platform vm
  - test: --platform firefox
  - test: --platform dartium
    install_dartium: true
dart:
  - 1.22.1
script:
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dart_dev test
  - pub run dart_dev coverage --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
