name: recompose_dart
version: 0.0.6
description:
   A collection of utilities for writing functional react components in dart
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/recompose_dart
dependencies:
  built_redux: "^0.0.1"
  over_react: "^1.6.0"
  w_flux: "^2.6.0"

dev_dependencies:
  built_value: "^1.0.0"
  built_collection: "^1.3.0"
  build: ^0.7.0
  build_runner: ^0.3.0
  built_value_generator: ^1.0.0
  source_gen: '>=0.5.0+03 <0.6.0'
  coverage: "^0.7.3"
  dart_dev: "^1.0.0"
  dart_style: ">=0.2.0 <0.3.0"
  dartdoc: ">=0.8.0 <=0.10.0"
  test: "^0.12.6+2"

transformers:
  - over_react
  - $dart2js
  - test/pub_serve:
      $include: test/**.dart

environment:
  sdk: ">=1.17.1 <2.0.0"
