name: recompose_dart

dependencies:
  built_redux:
    path: ../built_redux
  over_react: "^1.6.0"

dev_dependencies:
  built_value: "^1.0.0"
  built_collection: "^1.3.0"
  build: ^0.7.0
  build_runner: ^0.3.0
  built_value_generator: ^1.0.0
  source_gen: '>=0.5.0+03 <0.6.0'
  test: "^0.12.6+2"
  w_flux: "^2.6.0"

transformers:
  - over_react
  - $dart2js
  - test/pub_serve:
      $include: test/**.dart

environment:
  sdk: ">=1.17.1 <2.0.0"
